server:
  port: 8090
  servlet:
    context-path: /api
#  session:
#      timeout: 86400
  #servlet-path: "*.html"

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/myvedios?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#jms:
#    pub-sub-domain: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

mybatis:
#  typeAliasesPackage: "com.demo.graduationuser.*.entity"
  typeAliasesPackage: "com.graduation.myvedios.entity.*"
  mapperLocations: "mapper/sqlMapper/*Mapper.xml"
  enabledCache: true
  order: "BEFORE"

# 通用Mapper配置
mapper.plugin: tk.mybatis.mapper.generator.MapperPlugin
mapper.Mapper: tk.mybatis.mapper.common.Mapper
